"use strict"

import "./libs/dayjs.js"
import "./styles/global.css"
import "./styles/index.css"
import "./styles/schedule.css"
import "./modules/form/show-modal.js"
import "./modules/form/submit.js"
import "./modules/schedules/input-date.js"
import "./modules/page-load.js"